--config-locations "C:\Users\Vlad\Documents\ytdlp-commandline\yt-dlp-base.conf"

--format "ba/ba*"
--format-sort "hasaud,abr"

--extract-audio 
--embed-thumbnail 
--audio-quality 0 
--audio-format mp3 